name: ui
description: "Ui package"
version: 0.0.1
homepage:

environment:
  sdk: '>=3.9.0 <4.0.0'
  flutter: ">=3.38.0"

resolution: workspace

dependencies:
  flutter:
    sdk: flutter
  meta: any


flutter:
  uses-material-design: true
  shaders:
    - assets/shaders/shimmer.frag